
namespace UI.Desktop.Forms
{
    partial class ViewDetallePedido
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ViewDetallePedido));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtnombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtdescripcion = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtunidad = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtpreciounit = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtstock = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnBuscar = new Bunifu.UI.WinForms.BunifuImageButton();
            this.btnAgregar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtsubtotal = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnCancelar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtcantidad = new Bunifu.UI.WinForms.BunifuTextBox();
            this.SuspendLayout();
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel5.Location = new System.Drawing.Point(206, 12);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(185, 21);
            this.bunifuLabel5.TabIndex = 65;
            this.bunifuLabel5.Text = "Informacion de Material";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.Location = new System.Drawing.Point(59, 75);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(58, 17);
            this.bunifuLabel1.TabIndex = 66;
            this.bunifuLabel1.Text = "Nombre :";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.Location = new System.Drawing.Point(37, 125);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(80, 17);
            this.bunifuLabel2.TabIndex = 67;
            this.bunifuLabel2.Text = "Descripcion :";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.Location = new System.Drawing.Point(286, 125);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(52, 17);
            this.bunifuLabel3.TabIndex = 68;
            this.bunifuLabel3.Text = "Unidad :";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.Location = new System.Drawing.Point(17, 173);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(100, 17);
            this.bunifuLabel4.TabIndex = 69;
            this.bunifuLabel4.Text = "Precio Unitario :";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.Location = new System.Drawing.Point(294, 172);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(41, 17);
            this.bunifuLabel6.TabIndex = 70;
            this.bunifuLabel6.Text = "Stock :";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtnombre
            // 
            this.txtnombre.AcceptsReturn = false;
            this.txtnombre.AcceptsTab = false;
            this.txtnombre.AnimationSpeed = 200;
            this.txtnombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtnombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtnombre.BackColor = System.Drawing.Color.Transparent;
            this.txtnombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtnombre.BackgroundImage")));
            this.txtnombre.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtnombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtnombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtnombre.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtnombre.BorderRadius = 1;
            this.txtnombre.BorderThickness = 1;
            this.txtnombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtnombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtnombre.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtnombre.DefaultText = "";
            this.txtnombre.FillColor = System.Drawing.Color.White;
            this.txtnombre.HideSelection = true;
            this.txtnombre.IconLeft = null;
            this.txtnombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtnombre.IconPadding = 10;
            this.txtnombre.IconRight = null;
            this.txtnombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtnombre.Lines = new string[0];
            this.txtnombre.Location = new System.Drawing.Point(124, 70);
            this.txtnombre.MaxLength = 32767;
            this.txtnombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtnombre.Modified = false;
            this.txtnombre.Multiline = false;
            this.txtnombre.Name = "txtnombre";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtnombre.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtnombre.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtnombre.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtnombre.OnIdleState = stateProperties4;
            this.txtnombre.Padding = new System.Windows.Forms.Padding(3);
            this.txtnombre.PasswordChar = '\0';
            this.txtnombre.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtnombre.PlaceholderText = "Enter text";
            this.txtnombre.ReadOnly = false;
            this.txtnombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtnombre.SelectedText = "";
            this.txtnombre.SelectionLength = 0;
            this.txtnombre.SelectionStart = 0;
            this.txtnombre.ShortcutsEnabled = true;
            this.txtnombre.Size = new System.Drawing.Size(146, 32);
            this.txtnombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtnombre.TabIndex = 71;
            this.txtnombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtnombre.TextMarginBottom = 0;
            this.txtnombre.TextMarginLeft = 3;
            this.txtnombre.TextMarginTop = 0;
            this.txtnombre.TextPlaceholder = "Enter text";
            this.txtnombre.UseSystemPasswordChar = false;
            this.txtnombre.WordWrap = true;
            // 
            // txtdescripcion
            // 
            this.txtdescripcion.AcceptsReturn = false;
            this.txtdescripcion.AcceptsTab = false;
            this.txtdescripcion.AnimationSpeed = 200;
            this.txtdescripcion.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtdescripcion.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtdescripcion.BackColor = System.Drawing.Color.Transparent;
            this.txtdescripcion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtdescripcion.BackgroundImage")));
            this.txtdescripcion.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtdescripcion.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtdescripcion.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtdescripcion.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtdescripcion.BorderRadius = 1;
            this.txtdescripcion.BorderThickness = 1;
            this.txtdescripcion.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtdescripcion.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtdescripcion.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtdescripcion.DefaultText = "";
            this.txtdescripcion.Enabled = false;
            this.txtdescripcion.FillColor = System.Drawing.Color.White;
            this.txtdescripcion.HideSelection = true;
            this.txtdescripcion.IconLeft = null;
            this.txtdescripcion.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtdescripcion.IconPadding = 10;
            this.txtdescripcion.IconRight = null;
            this.txtdescripcion.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtdescripcion.Lines = new string[0];
            this.txtdescripcion.Location = new System.Drawing.Point(124, 118);
            this.txtdescripcion.MaxLength = 32767;
            this.txtdescripcion.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtdescripcion.Modified = false;
            this.txtdescripcion.Multiline = false;
            this.txtdescripcion.Name = "txtdescripcion";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtdescripcion.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtdescripcion.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtdescripcion.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtdescripcion.OnIdleState = stateProperties8;
            this.txtdescripcion.Padding = new System.Windows.Forms.Padding(3);
            this.txtdescripcion.PasswordChar = '\0';
            this.txtdescripcion.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtdescripcion.PlaceholderText = "Enter text";
            this.txtdescripcion.ReadOnly = false;
            this.txtdescripcion.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtdescripcion.SelectedText = "";
            this.txtdescripcion.SelectionLength = 0;
            this.txtdescripcion.SelectionStart = 0;
            this.txtdescripcion.ShortcutsEnabled = true;
            this.txtdescripcion.Size = new System.Drawing.Size(146, 32);
            this.txtdescripcion.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtdescripcion.TabIndex = 72;
            this.txtdescripcion.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtdescripcion.TextMarginBottom = 0;
            this.txtdescripcion.TextMarginLeft = 3;
            this.txtdescripcion.TextMarginTop = 0;
            this.txtdescripcion.TextPlaceholder = "Enter text";
            this.txtdescripcion.UseSystemPasswordChar = false;
            this.txtdescripcion.WordWrap = true;
            // 
            // txtunidad
            // 
            this.txtunidad.AcceptsReturn = false;
            this.txtunidad.AcceptsTab = false;
            this.txtunidad.AnimationSpeed = 200;
            this.txtunidad.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtunidad.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtunidad.BackColor = System.Drawing.Color.Transparent;
            this.txtunidad.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtunidad.BackgroundImage")));
            this.txtunidad.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtunidad.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtunidad.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtunidad.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtunidad.BorderRadius = 1;
            this.txtunidad.BorderThickness = 1;
            this.txtunidad.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtunidad.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtunidad.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtunidad.DefaultText = "";
            this.txtunidad.Enabled = false;
            this.txtunidad.FillColor = System.Drawing.Color.White;
            this.txtunidad.HideSelection = true;
            this.txtunidad.IconLeft = null;
            this.txtunidad.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtunidad.IconPadding = 10;
            this.txtunidad.IconRight = null;
            this.txtunidad.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtunidad.Lines = new string[0];
            this.txtunidad.Location = new System.Drawing.Point(344, 118);
            this.txtunidad.MaxLength = 32767;
            this.txtunidad.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtunidad.Modified = false;
            this.txtunidad.Multiline = false;
            this.txtunidad.Name = "txtunidad";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtunidad.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtunidad.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtunidad.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtunidad.OnIdleState = stateProperties12;
            this.txtunidad.Padding = new System.Windows.Forms.Padding(3);
            this.txtunidad.PasswordChar = '\0';
            this.txtunidad.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtunidad.PlaceholderText = "Enter text";
            this.txtunidad.ReadOnly = false;
            this.txtunidad.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtunidad.SelectedText = "";
            this.txtunidad.SelectionLength = 0;
            this.txtunidad.SelectionStart = 0;
            this.txtunidad.ShortcutsEnabled = true;
            this.txtunidad.Size = new System.Drawing.Size(189, 32);
            this.txtunidad.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtunidad.TabIndex = 73;
            this.txtunidad.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtunidad.TextMarginBottom = 0;
            this.txtunidad.TextMarginLeft = 3;
            this.txtunidad.TextMarginTop = 0;
            this.txtunidad.TextPlaceholder = "Enter text";
            this.txtunidad.UseSystemPasswordChar = false;
            this.txtunidad.WordWrap = true;
            // 
            // txtpreciounit
            // 
            this.txtpreciounit.AcceptsReturn = false;
            this.txtpreciounit.AcceptsTab = false;
            this.txtpreciounit.AnimationSpeed = 200;
            this.txtpreciounit.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtpreciounit.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtpreciounit.BackColor = System.Drawing.Color.Transparent;
            this.txtpreciounit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtpreciounit.BackgroundImage")));
            this.txtpreciounit.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtpreciounit.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtpreciounit.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtpreciounit.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtpreciounit.BorderRadius = 1;
            this.txtpreciounit.BorderThickness = 1;
            this.txtpreciounit.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtpreciounit.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtpreciounit.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtpreciounit.DefaultText = "";
            this.txtpreciounit.Enabled = false;
            this.txtpreciounit.FillColor = System.Drawing.Color.White;
            this.txtpreciounit.HideSelection = true;
            this.txtpreciounit.IconLeft = null;
            this.txtpreciounit.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtpreciounit.IconPadding = 10;
            this.txtpreciounit.IconRight = null;
            this.txtpreciounit.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtpreciounit.Lines = new string[0];
            this.txtpreciounit.Location = new System.Drawing.Point(124, 166);
            this.txtpreciounit.MaxLength = 32767;
            this.txtpreciounit.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtpreciounit.Modified = false;
            this.txtpreciounit.Multiline = false;
            this.txtpreciounit.Name = "txtpreciounit";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtpreciounit.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtpreciounit.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtpreciounit.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtpreciounit.OnIdleState = stateProperties16;
            this.txtpreciounit.Padding = new System.Windows.Forms.Padding(3);
            this.txtpreciounit.PasswordChar = '\0';
            this.txtpreciounit.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtpreciounit.PlaceholderText = "Enter text";
            this.txtpreciounit.ReadOnly = false;
            this.txtpreciounit.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtpreciounit.SelectedText = "";
            this.txtpreciounit.SelectionLength = 0;
            this.txtpreciounit.SelectionStart = 0;
            this.txtpreciounit.ShortcutsEnabled = true;
            this.txtpreciounit.Size = new System.Drawing.Size(146, 32);
            this.txtpreciounit.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtpreciounit.TabIndex = 74;
            this.txtpreciounit.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtpreciounit.TextMarginBottom = 0;
            this.txtpreciounit.TextMarginLeft = 3;
            this.txtpreciounit.TextMarginTop = 0;
            this.txtpreciounit.TextPlaceholder = "Enter text";
            this.txtpreciounit.UseSystemPasswordChar = false;
            this.txtpreciounit.WordWrap = true;
            // 
            // txtstock
            // 
            this.txtstock.AcceptsReturn = false;
            this.txtstock.AcceptsTab = false;
            this.txtstock.AnimationSpeed = 200;
            this.txtstock.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtstock.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtstock.BackColor = System.Drawing.Color.Transparent;
            this.txtstock.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtstock.BackgroundImage")));
            this.txtstock.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtstock.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtstock.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtstock.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtstock.BorderRadius = 1;
            this.txtstock.BorderThickness = 1;
            this.txtstock.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtstock.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtstock.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtstock.DefaultText = "";
            this.txtstock.Enabled = false;
            this.txtstock.FillColor = System.Drawing.Color.White;
            this.txtstock.HideSelection = true;
            this.txtstock.IconLeft = null;
            this.txtstock.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtstock.IconPadding = 10;
            this.txtstock.IconRight = null;
            this.txtstock.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtstock.Lines = new string[0];
            this.txtstock.Location = new System.Drawing.Point(344, 166);
            this.txtstock.MaxLength = 32767;
            this.txtstock.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtstock.Modified = false;
            this.txtstock.Multiline = false;
            this.txtstock.Name = "txtstock";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtstock.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtstock.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtstock.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtstock.OnIdleState = stateProperties20;
            this.txtstock.Padding = new System.Windows.Forms.Padding(3);
            this.txtstock.PasswordChar = '\0';
            this.txtstock.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtstock.PlaceholderText = "Enter text";
            this.txtstock.ReadOnly = false;
            this.txtstock.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtstock.SelectedText = "";
            this.txtstock.SelectionLength = 0;
            this.txtstock.SelectionStart = 0;
            this.txtstock.ShortcutsEnabled = true;
            this.txtstock.Size = new System.Drawing.Size(189, 32);
            this.txtstock.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtstock.TabIndex = 75;
            this.txtstock.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtstock.TextMarginBottom = 0;
            this.txtstock.TextMarginLeft = 3;
            this.txtstock.TextMarginTop = 0;
            this.txtstock.TextPlaceholder = "Enter text";
            this.txtstock.UseSystemPasswordChar = false;
            this.txtstock.WordWrap = true;
            // 
            // btnBuscar
            // 
            this.btnBuscar.ActiveImage = null;
            this.btnBuscar.AllowAnimations = true;
            this.btnBuscar.AllowBuffering = false;
            this.btnBuscar.AllowToggling = false;
            this.btnBuscar.AllowZooming = true;
            this.btnBuscar.AllowZoomingOnFocus = false;
            this.btnBuscar.BackColor = System.Drawing.Color.Transparent;
            this.btnBuscar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnBuscar.ErrorImage = ((System.Drawing.Image)(resources.GetObject("btnBuscar.ErrorImage")));
            this.btnBuscar.FadeWhenInactive = false;
            this.btnBuscar.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.btnBuscar.Image = ((System.Drawing.Image)(resources.GetObject("btnBuscar.Image")));
            this.btnBuscar.ImageActive = null;
            this.btnBuscar.ImageLocation = null;
            this.btnBuscar.ImageMargin = 0;
            this.btnBuscar.ImageSize = new System.Drawing.Size(34, 34);
            this.btnBuscar.ImageZoomSize = new System.Drawing.Size(35, 35);
            this.btnBuscar.InitialImage = ((System.Drawing.Image)(resources.GetObject("btnBuscar.InitialImage")));
            this.btnBuscar.Location = new System.Drawing.Point(294, 70);
            this.btnBuscar.Name = "btnBuscar";
            this.btnBuscar.Rotation = 0;
            this.btnBuscar.ShowActiveImage = true;
            this.btnBuscar.ShowCursorChanges = true;
            this.btnBuscar.ShowImageBorders = false;
            this.btnBuscar.ShowSizeMarkers = false;
            this.btnBuscar.Size = new System.Drawing.Size(35, 35);
            this.btnBuscar.TabIndex = 76;
            this.btnBuscar.ToolTipText = "";
            this.btnBuscar.WaitOnLoad = false;
            this.btnBuscar.Zoom = 0;
            this.btnBuscar.ZoomSpeed = 10;
            this.btnBuscar.Click += new System.EventHandler(this.btnBuscar_Click);
            // 
            // btnAgregar
            // 
            this.btnAgregar.AllowAnimations = true;
            this.btnAgregar.AllowMouseEffects = true;
            this.btnAgregar.AllowToggling = false;
            this.btnAgregar.AnimationSpeed = 200;
            this.btnAgregar.AutoGenerateColors = false;
            this.btnAgregar.AutoRoundBorders = false;
            this.btnAgregar.AutoSizeLeftIcon = true;
            this.btnAgregar.AutoSizeRightIcon = true;
            this.btnAgregar.BackColor = System.Drawing.Color.Transparent;
            this.btnAgregar.BackColor1 = System.Drawing.Color.Gray;
            this.btnAgregar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAgregar.BackgroundImage")));
            this.btnAgregar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAgregar.ButtonText = "Agregar ";
            this.btnAgregar.ButtonTextMarginLeft = 0;
            this.btnAgregar.ColorContrastOnClick = 45;
            this.btnAgregar.ColorContrastOnHover = 45;
            this.btnAgregar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnAgregar.CustomizableEdges = borderEdges1;
            this.btnAgregar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAgregar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAgregar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAgregar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAgregar.Enabled = false;
            this.btnAgregar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAgregar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnAgregar.ForeColor = System.Drawing.Color.White;
            this.btnAgregar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAgregar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAgregar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAgregar.IconMarginLeft = 11;
            this.btnAgregar.IconPadding = 10;
            this.btnAgregar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAgregar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAgregar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAgregar.IconSize = 25;
            this.btnAgregar.IdleBorderColor = System.Drawing.Color.Black;
            this.btnAgregar.IdleBorderRadius = 1;
            this.btnAgregar.IdleBorderThickness = 1;
            this.btnAgregar.IdleFillColor = System.Drawing.Color.Gray;
            this.btnAgregar.IdleIconLeftImage = null;
            this.btnAgregar.IdleIconRightImage = null;
            this.btnAgregar.IndicateFocus = false;
            this.btnAgregar.Location = new System.Drawing.Point(85, 285);
            this.btnAgregar.Name = "btnAgregar";
            this.btnAgregar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAgregar.OnDisabledState.BorderRadius = 1;
            this.btnAgregar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAgregar.OnDisabledState.BorderThickness = 1;
            this.btnAgregar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAgregar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAgregar.OnDisabledState.IconLeftImage = null;
            this.btnAgregar.OnDisabledState.IconRightImage = null;
            this.btnAgregar.onHoverState.BorderColor = System.Drawing.Color.Black;
            this.btnAgregar.onHoverState.BorderRadius = 1;
            this.btnAgregar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAgregar.onHoverState.BorderThickness = 1;
            this.btnAgregar.onHoverState.FillColor = System.Drawing.Color.Silver;
            this.btnAgregar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAgregar.onHoverState.IconLeftImage = null;
            this.btnAgregar.onHoverState.IconRightImage = null;
            this.btnAgregar.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnAgregar.OnIdleState.BorderRadius = 1;
            this.btnAgregar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAgregar.OnIdleState.BorderThickness = 1;
            this.btnAgregar.OnIdleState.FillColor = System.Drawing.Color.Gray;
            this.btnAgregar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAgregar.OnIdleState.IconLeftImage = null;
            this.btnAgregar.OnIdleState.IconRightImage = null;
            this.btnAgregar.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.btnAgregar.OnPressedState.BorderRadius = 1;
            this.btnAgregar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAgregar.OnPressedState.BorderThickness = 1;
            this.btnAgregar.OnPressedState.FillColor = System.Drawing.Color.Silver;
            this.btnAgregar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAgregar.OnPressedState.IconLeftImage = null;
            this.btnAgregar.OnPressedState.IconRightImage = null;
            this.btnAgregar.Size = new System.Drawing.Size(167, 39);
            this.btnAgregar.TabIndex = 77;
            this.btnAgregar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAgregar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAgregar.TextMarginLeft = 0;
            this.btnAgregar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAgregar.UseDefaultRadiusAndThickness = true;
            this.btnAgregar.Click += new System.EventHandler(this.btnAgregar_Click);
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel7.Location = new System.Drawing.Point(54, 222);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(63, 17);
            this.bunifuLabel7.TabIndex = 78;
            this.bunifuLabel7.Text = "SubTotal :";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtsubtotal
            // 
            this.txtsubtotal.AcceptsReturn = false;
            this.txtsubtotal.AcceptsTab = false;
            this.txtsubtotal.AnimationSpeed = 200;
            this.txtsubtotal.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtsubtotal.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtsubtotal.BackColor = System.Drawing.Color.Transparent;
            this.txtsubtotal.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtsubtotal.BackgroundImage")));
            this.txtsubtotal.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtsubtotal.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtsubtotal.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtsubtotal.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtsubtotal.BorderRadius = 1;
            this.txtsubtotal.BorderThickness = 1;
            this.txtsubtotal.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtsubtotal.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtsubtotal.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtsubtotal.DefaultText = "";
            this.txtsubtotal.Enabled = false;
            this.txtsubtotal.FillColor = System.Drawing.Color.White;
            this.txtsubtotal.HideSelection = true;
            this.txtsubtotal.IconLeft = null;
            this.txtsubtotal.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtsubtotal.IconPadding = 10;
            this.txtsubtotal.IconRight = null;
            this.txtsubtotal.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtsubtotal.Lines = new string[0];
            this.txtsubtotal.Location = new System.Drawing.Point(124, 214);
            this.txtsubtotal.MaxLength = 32767;
            this.txtsubtotal.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtsubtotal.Modified = false;
            this.txtsubtotal.Multiline = false;
            this.txtsubtotal.Name = "txtsubtotal";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtsubtotal.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtsubtotal.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtsubtotal.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtsubtotal.OnIdleState = stateProperties24;
            this.txtsubtotal.Padding = new System.Windows.Forms.Padding(3);
            this.txtsubtotal.PasswordChar = '\0';
            this.txtsubtotal.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtsubtotal.PlaceholderText = "Enter text";
            this.txtsubtotal.ReadOnly = false;
            this.txtsubtotal.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtsubtotal.SelectedText = "";
            this.txtsubtotal.SelectionLength = 0;
            this.txtsubtotal.SelectionStart = 0;
            this.txtsubtotal.ShortcutsEnabled = true;
            this.txtsubtotal.Size = new System.Drawing.Size(146, 32);
            this.txtsubtotal.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtsubtotal.TabIndex = 79;
            this.txtsubtotal.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtsubtotal.TextMarginBottom = 0;
            this.txtsubtotal.TextMarginLeft = 3;
            this.txtsubtotal.TextMarginTop = 0;
            this.txtsubtotal.TextPlaceholder = "Enter text";
            this.txtsubtotal.UseSystemPasswordChar = false;
            this.txtsubtotal.WordWrap = true;
            // 
            // btnCancelar
            // 
            this.btnCancelar.AllowAnimations = true;
            this.btnCancelar.AllowMouseEffects = true;
            this.btnCancelar.AllowToggling = false;
            this.btnCancelar.AnimationSpeed = 200;
            this.btnCancelar.AutoGenerateColors = false;
            this.btnCancelar.AutoRoundBorders = false;
            this.btnCancelar.AutoSizeLeftIcon = true;
            this.btnCancelar.AutoSizeRightIcon = true;
            this.btnCancelar.BackColor = System.Drawing.Color.Transparent;
            this.btnCancelar.BackColor1 = System.Drawing.Color.Gray;
            this.btnCancelar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCancelar.BackgroundImage")));
            this.btnCancelar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancelar.ButtonText = "Cancelar";
            this.btnCancelar.ButtonTextMarginLeft = 0;
            this.btnCancelar.ColorContrastOnClick = 45;
            this.btnCancelar.ColorContrastOnHover = 45;
            this.btnCancelar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnCancelar.CustomizableEdges = borderEdges2;
            this.btnCancelar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCancelar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancelar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancelar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancelar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCancelar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnCancelar.ForeColor = System.Drawing.Color.White;
            this.btnCancelar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancelar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancelar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCancelar.IconMarginLeft = 11;
            this.btnCancelar.IconPadding = 10;
            this.btnCancelar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancelar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancelar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCancelar.IconSize = 25;
            this.btnCancelar.IdleBorderColor = System.Drawing.Color.Black;
            this.btnCancelar.IdleBorderRadius = 1;
            this.btnCancelar.IdleBorderThickness = 1;
            this.btnCancelar.IdleFillColor = System.Drawing.Color.Gray;
            this.btnCancelar.IdleIconLeftImage = null;
            this.btnCancelar.IdleIconRightImage = null;
            this.btnCancelar.IndicateFocus = false;
            this.btnCancelar.Location = new System.Drawing.Point(286, 285);
            this.btnCancelar.Name = "btnCancelar";
            this.btnCancelar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancelar.OnDisabledState.BorderRadius = 1;
            this.btnCancelar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancelar.OnDisabledState.BorderThickness = 1;
            this.btnCancelar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancelar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancelar.OnDisabledState.IconLeftImage = null;
            this.btnCancelar.OnDisabledState.IconRightImage = null;
            this.btnCancelar.onHoverState.BorderColor = System.Drawing.Color.Black;
            this.btnCancelar.onHoverState.BorderRadius = 1;
            this.btnCancelar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancelar.onHoverState.BorderThickness = 1;
            this.btnCancelar.onHoverState.FillColor = System.Drawing.Color.Silver;
            this.btnCancelar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCancelar.onHoverState.IconLeftImage = null;
            this.btnCancelar.onHoverState.IconRightImage = null;
            this.btnCancelar.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnCancelar.OnIdleState.BorderRadius = 1;
            this.btnCancelar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancelar.OnIdleState.BorderThickness = 1;
            this.btnCancelar.OnIdleState.FillColor = System.Drawing.Color.Gray;
            this.btnCancelar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCancelar.OnIdleState.IconLeftImage = null;
            this.btnCancelar.OnIdleState.IconRightImage = null;
            this.btnCancelar.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.btnCancelar.OnPressedState.BorderRadius = 1;
            this.btnCancelar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancelar.OnPressedState.BorderThickness = 1;
            this.btnCancelar.OnPressedState.FillColor = System.Drawing.Color.Silver;
            this.btnCancelar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCancelar.OnPressedState.IconLeftImage = null;
            this.btnCancelar.OnPressedState.IconRightImage = null;
            this.btnCancelar.Size = new System.Drawing.Size(167, 39);
            this.btnCancelar.TabIndex = 80;
            this.btnCancelar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCancelar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCancelar.TextMarginLeft = 0;
            this.btnCancelar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCancelar.UseDefaultRadiusAndThickness = true;
            this.btnCancelar.Click += new System.EventHandler(this.btnCancelar_Click);
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.CursorType = null;
            this.bunifuLabel8.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel8.Location = new System.Drawing.Point(272, 222);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(63, 17);
            this.bunifuLabel8.TabIndex = 81;
            this.bunifuLabel8.Text = "Cantidad :";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtcantidad
            // 
            this.txtcantidad.AcceptsReturn = false;
            this.txtcantidad.AcceptsTab = false;
            this.txtcantidad.AnimationSpeed = 200;
            this.txtcantidad.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtcantidad.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtcantidad.BackColor = System.Drawing.Color.Transparent;
            this.txtcantidad.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtcantidad.BackgroundImage")));
            this.txtcantidad.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtcantidad.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtcantidad.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtcantidad.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtcantidad.BorderRadius = 1;
            this.txtcantidad.BorderThickness = 1;
            this.txtcantidad.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtcantidad.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtcantidad.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtcantidad.DefaultText = "";
            this.txtcantidad.FillColor = System.Drawing.Color.White;
            this.txtcantidad.HideSelection = true;
            this.txtcantidad.IconLeft = null;
            this.txtcantidad.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtcantidad.IconPadding = 10;
            this.txtcantidad.IconRight = null;
            this.txtcantidad.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtcantidad.Lines = new string[0];
            this.txtcantidad.Location = new System.Drawing.Point(344, 214);
            this.txtcantidad.MaxLength = 32767;
            this.txtcantidad.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtcantidad.Modified = false;
            this.txtcantidad.Multiline = false;
            this.txtcantidad.Name = "txtcantidad";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtcantidad.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtcantidad.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtcantidad.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtcantidad.OnIdleState = stateProperties28;
            this.txtcantidad.Padding = new System.Windows.Forms.Padding(3);
            this.txtcantidad.PasswordChar = '\0';
            this.txtcantidad.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtcantidad.PlaceholderText = "Enter text";
            this.txtcantidad.ReadOnly = false;
            this.txtcantidad.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtcantidad.SelectedText = "";
            this.txtcantidad.SelectionLength = 0;
            this.txtcantidad.SelectionStart = 0;
            this.txtcantidad.ShortcutsEnabled = true;
            this.txtcantidad.Size = new System.Drawing.Size(189, 32);
            this.txtcantidad.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtcantidad.TabIndex = 82;
            this.txtcantidad.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtcantidad.TextMarginBottom = 0;
            this.txtcantidad.TextMarginLeft = 3;
            this.txtcantidad.TextMarginTop = 0;
            this.txtcantidad.TextPlaceholder = "Enter text";
            this.txtcantidad.UseSystemPasswordChar = false;
            this.txtcantidad.WordWrap = true;
            //this.txtcantidad.TextChanged += new System.EventHandler(this.txtcantidad_TextChanged);
            // 
            // ViewDetallePedido
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(576, 362);
            this.Controls.Add(this.txtcantidad);
            this.Controls.Add(this.bunifuLabel8);
            this.Controls.Add(this.btnCancelar);
            this.Controls.Add(this.txtsubtotal);
            this.Controls.Add(this.bunifuLabel7);
            this.Controls.Add(this.btnAgregar);
            this.Controls.Add(this.btnBuscar);
            this.Controls.Add(this.txtstock);
            this.Controls.Add(this.txtpreciounit);
            this.Controls.Add(this.txtunidad);
            this.Controls.Add(this.txtdescripcion);
            this.Controls.Add(this.txtnombre);
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.bunifuLabel5);
            this.Name = "ViewDetallePedido";
            this.Text = "ViewDetallePedido";
            //this.Load += new System.EventHandler(this.ViewDetallePedido_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuTextBox txtnombre;
        private Bunifu.UI.WinForms.BunifuTextBox txtdescripcion;
        private Bunifu.UI.WinForms.BunifuTextBox txtunidad;
        private Bunifu.UI.WinForms.BunifuTextBox txtpreciounit;
        private Bunifu.UI.WinForms.BunifuTextBox txtstock;
        private Bunifu.UI.WinForms.BunifuImageButton btnBuscar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAgregar;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuTextBox txtsubtotal;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCancelar;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuTextBox txtcantidad;
    }
}