// ------------------------------------------------------------------------------
//  <auto-generated>
//      Este código lo generó el generador de pruebas automatizadas de IU.
//      Versión: 16.0.0.0
//
//      Los cambios realizados en este archivo pueden provocar un comportamiento incorrecto y se perderán si
//      se vuelve a generar el código.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITest_Gestion_Cliente
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Gestion Clientes
        /// </summary>
        public void RecordedMethod()
        {
            #region Variable Declarations
            WinEdit uIEditEdit = this.UIViewLogWindow.UIEntertextWindow.UIEditEdit;
            WinEdit uIEditEdit1 = this.UIViewLogWindow.UIEntertextWindow1.UIEditEdit;
            WinText uIIniciarSesionText = this.UIViewLogWindow.UIIniciarSesionWindow.UIIniciarSesionText;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            WinText uIGestionClientesText = this.UIViewPrincipalWindow.UIGestionClientesWindow.UIGestionClientesText;
            WinClient uIBtnRegistrarClient = this.UIViewPrincipalWindow.UIBtnRegistrarWindow.UIBtnRegistrarClient;
            WinEdit uIEditEdit2 = this.UIViewRegistroClienteWindow.UIEntertextWindow.UIEditEdit;
            WinClient uITxtNombreClient = this.UIViewRegistroClienteWindow.UITxtNombreWindow.UITxtNombreClient;
            WinEdit uIEditEdit3 = this.UIViewRegistroClienteWindow.UIEntertextWindow1.UIEditEdit;
            WinClient uITxtApellidoClient = this.UIViewRegistroClienteWindow.UITxtApellidoWindow.UITxtApellidoClient;
            WinEdit uIEditEdit4 = this.UIViewRegistroClienteWindow.UIEntertextWindow2.UIEditEdit;
            WinClient uITxtDireccionClient = this.UIViewRegistroClienteWindow.UITxtDireccionWindow.UITxtDireccionClient;
            WinEdit uIEditEdit5 = this.UIViewRegistroClienteWindow.UIEntertextWindow3.UIEditEdit;
            WinEdit uIEditEdit6 = this.UIViewRegistroClienteWindow.UIEntertextWindow4.UIEditEdit;
            WinClient uIViewRegistroClienteClient = this.UIViewRegistroClienteWindow.UIViewRegistroClienteClient;
            WinClient uITxtTelefonoClient = this.UIViewRegistroClienteWindow.UITxtTelefonoWindow.UITxtTelefonoClient;
            WinEdit uIEditEdit7 = this.UIViewRegistroClienteWindow.UIEntertextWindow5.UIEditEdit;
            WinEdit uIEditEdit8 = this.UIViewRegistroClienteWindow.UIEntertextWindow6.UIEditEdit;
            WinText uIRegistrarText = this.UIViewRegistroClienteWindow.UIRegistrarWindow.UIRegistrarText;
            WinButton uIOKButton1 = this.UIConfirmacionWindow.UIOKWindow.UIOKButton;
            WinClient uIBtnBuscarClient = this.UIViewPrincipalWindow.UIBtnBuscarWindow.UIBtnBuscarClient;
            #endregion

            // Iniciar '%USERPROFILE%\Downloads\DDD (1)\DDD\UI.Desktop\bin\Debug\UI.Desktop.exe'
            ApplicationUnderTest uIViewLogWindow = ApplicationUnderTest.Launch(this.RecordedMethodParams.UIViewLogWindowExePath, this.RecordedMethodParams.UIViewLogWindowAlternateExePath);

            // Escribir 'Admin' en cuadro de texto 'edit'
            uIEditEdit.Text = this.RecordedMethodParams.UIEditEditText;

            // Escribir '123qweu0' en cuadro de texto 'edit'
            uIEditEdit1.Text = this.RecordedMethodParams.UIEditEditText1;

            // Clic 'Iniciar Sesion' etiqueta
            Mouse.Click(uIIniciarSesionText, new Point(24, 11));

            // Clic 'OK' botón
            Mouse.Click(uIOKButton, new Point(36, 12));

            // Clic 'Gestion Clientes' etiqueta
            Mouse.Click(uIGestionClientesText, new Point(43, 0));

            // Clic 'btnRegistrar' cliente
            Mouse.Click(uIBtnRegistrarClient, new Point(15, 14));

            // Escribir '123' en cuadro de texto 'edit'
            uIEditEdit2.Text = this.RecordedMethodParams.UIEditEditText2;

            // Clic 'txtNombre' cliente
            Mouse.Click(uITxtNombreClient, new Point(45, 6));

            // Escribir 'Steve' en cuadro de texto 'edit'
            uIEditEdit3.Text = this.RecordedMethodParams.UIEditEditText3;

            // Clic 'txtApellido' cliente
            Mouse.Click(uITxtApellidoClient, new Point(56, 6));

            // Escribir 'Mamani' en cuadro de texto 'edit'
            uIEditEdit4.Text = this.RecordedMethodParams.UIEditEditText4;

            // Clic 'txtDireccion' cliente
            Mouse.Click(uITxtDireccionClient, new Point(58, 36));

            // Escribir 'Tacna' en cuadro de texto 'edit'
            uIEditEdit5.Text = this.RecordedMethodParams.UIEditEditText5;

            // Escribir 'Steve2021' en cuadro de texto 'edit'
            uIEditEdit6.Text = this.RecordedMethodParams.UIEditEditText6;

            // Clic 'ViewRegistroCliente' cliente
            Mouse.Click(uIViewRegistroClienteClient, new Point(255, 362));

            // Clic 'txtTelefono' cliente
            Mouse.Click(uITxtTelefonoClient, new Point(95, 3));

            // Escribir '321' en cuadro de texto 'edit'
            uIEditEdit7.Text = this.RecordedMethodParams.UIEditEditText7;

            // Clic 'edit' cuadro de texto
            Mouse.Click(uIEditEdit8, new Point(61, 12));

            // Escribir '********' en cuadro de texto 'edit'
            Keyboard.SendKeys(uIEditEdit8, this.RecordedMethodParams.UIEditEditSendKeys, true);

            // Clic 'Registrar' etiqueta
            Mouse.Click(uIRegistrarText, new Point(47, 0));

            // Clic 'OK' botón
            Mouse.Click(uIOKButton1, new Point(30, 11));

            // Clic 'btnBuscar' cliente
            Mouse.Click(uIBtnBuscarClient, new Point(14, 15));
        }
        
        #region Properties
        public virtual RecordedMethodParams RecordedMethodParams
        {
            get
            {
                if ((this.mRecordedMethodParams == null))
                {
                    this.mRecordedMethodParams = new RecordedMethodParams();
                }
                return this.mRecordedMethodParams;
            }
        }
        
        public UIViewLogWindow UIViewLogWindow
        {
            get
            {
                if ((this.mUIViewLogWindow == null))
                {
                    this.mUIViewLogWindow = new UIViewLogWindow();
                }
                return this.mUIViewLogWindow;
            }
        }
        
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow();
                }
                return this.mUIOKWindow;
            }
        }
        
        public UIViewPrincipalWindow UIViewPrincipalWindow
        {
            get
            {
                if ((this.mUIViewPrincipalWindow == null))
                {
                    this.mUIViewPrincipalWindow = new UIViewPrincipalWindow();
                }
                return this.mUIViewPrincipalWindow;
            }
        }
        
        public UIViewRegistroClienteWindow UIViewRegistroClienteWindow
        {
            get
            {
                if ((this.mUIViewRegistroClienteWindow == null))
                {
                    this.mUIViewRegistroClienteWindow = new UIViewRegistroClienteWindow();
                }
                return this.mUIViewRegistroClienteWindow;
            }
        }
        
        public UIConfirmacionWindow UIConfirmacionWindow
        {
            get
            {
                if ((this.mUIConfirmacionWindow == null))
                {
                    this.mUIConfirmacionWindow = new UIConfirmacionWindow();
                }
                return this.mUIConfirmacionWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethodParams mRecordedMethodParams;
        
        private UIViewLogWindow mUIViewLogWindow;
        
        private UIOKWindow mUIOKWindow;
        
        private UIViewPrincipalWindow mUIViewPrincipalWindow;
        
        private UIViewRegistroClienteWindow mUIViewRegistroClienteWindow;
        
        private UIConfirmacionWindow mUIConfirmacionWindow;
        #endregion
    }
    
    /// <summary>
    /// Parámetros que se van a pasar a 'RecordedMethod'
    /// </summary>
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class RecordedMethodParams
    {
        
        #region Fields
        /// <summary>
        /// Iniciar '%USERPROFILE%\Downloads\DDD (1)\DDD\UI.Desktop\bin\Debug\UI.Desktop.exe'
        /// </summary>
        public string UIViewLogWindowExePath = "C:\\Users\\USUARIO\\Downloads\\DDD (1)\\DDD\\UI.Desktop\\bin\\Debug\\UI.Desktop.exe";
        
        /// <summary>
        /// Iniciar '%USERPROFILE%\Downloads\DDD (1)\DDD\UI.Desktop\bin\Debug\UI.Desktop.exe'
        /// </summary>
        public string UIViewLogWindowAlternateExePath = "%USERPROFILE%\\Downloads\\DDD (1)\\DDD\\UI.Desktop\\bin\\Debug\\UI.Desktop.exe";
        
        /// <summary>
        /// Escribir 'Admin' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText = "Admin";
        
        /// <summary>
        /// Escribir '123qweu0' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText1 = "123qweu0";
        
        /// <summary>
        /// Escribir '123' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText2 = "123";
        
        /// <summary>
        /// Escribir 'Steve' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText3 = "Steve";
        
        /// <summary>
        /// Escribir 'Mamani' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText4 = "Mamani";
        
        /// <summary>
        /// Escribir 'Tacna' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText5 = "Tacna";
        
        /// <summary>
        /// Escribir 'Steve2021' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText6 = "Steve2021";
        
        /// <summary>
        /// Escribir '321' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText7 = "321";
        
        /// <summary>
        /// Escribir '********' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditSendKeys = "mOL/lXDUSd/hy7K5BZnJEA==";
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIViewLogWindow : WinWindow
    {
        
        public UIViewLogWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "ViewLog";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("ViewLog");
            #endregion
        }
        
        #region Properties
        public UIEntertextWindow UIEntertextWindow
        {
            get
            {
                if ((this.mUIEntertextWindow == null))
                {
                    this.mUIEntertextWindow = new UIEntertextWindow(this);
                }
                return this.mUIEntertextWindow;
            }
        }
        
        public UIEntertextWindow1 UIEntertextWindow1
        {
            get
            {
                if ((this.mUIEntertextWindow1 == null))
                {
                    this.mUIEntertextWindow1 = new UIEntertextWindow1(this);
                }
                return this.mUIEntertextWindow1;
            }
        }
        
        public UIIniciarSesionWindow UIIniciarSesionWindow
        {
            get
            {
                if ((this.mUIIniciarSesionWindow == null))
                {
                    this.mUIIniciarSesionWindow = new UIIniciarSesionWindow(this);
                }
                return this.mUIIniciarSesionWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIEntertextWindow mUIEntertextWindow;
        
        private UIEntertextWindow1 mUIEntertextWindow1;
        
        private UIIniciarSesionWindow mUIIniciarSesionWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow : WinWindow
    {
        
        public UIEntertextWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("ViewLog");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewLog");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow1 : WinWindow
    {
        
        public UIEntertextWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.WindowTitles.Add("ViewLog");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewLog");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIIniciarSesionWindow : WinWindow
    {
        
        public UIIniciarSesionWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "Label";
            this.WindowTitles.Add("ViewLog");
            #endregion
        }
        
        #region Properties
        public WinText UIIniciarSesionText
        {
            get
            {
                if ((this.mUIIniciarSesionText == null))
                {
                    this.mUIIniciarSesionText = new WinText(this);
                    #region Criterio de búsqueda
                    this.mUIIniciarSesionText.SearchProperties[WinText.PropertyNames.Name] = "Iniciar Sesion";
                    this.mUIIniciarSesionText.WindowTitles.Add("ViewLog");
                    #endregion
                }
                return this.mUIIniciarSesionText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIIniciarSesionText;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "OK";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Button";
            this.WindowTitles.Add("OK");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Criterio de búsqueda
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("OK");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIViewPrincipalWindow : WinWindow
    {
        
        public UIViewPrincipalWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "ViewPrincipal";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public UIGestionClientesWindow UIGestionClientesWindow
        {
            get
            {
                if ((this.mUIGestionClientesWindow == null))
                {
                    this.mUIGestionClientesWindow = new UIGestionClientesWindow(this);
                }
                return this.mUIGestionClientesWindow;
            }
        }
        
        public UIBtnRegistrarWindow UIBtnRegistrarWindow
        {
            get
            {
                if ((this.mUIBtnRegistrarWindow == null))
                {
                    this.mUIBtnRegistrarWindow = new UIBtnRegistrarWindow(this);
                }
                return this.mUIBtnRegistrarWindow;
            }
        }
        
        public UIBtnBuscarWindow UIBtnBuscarWindow
        {
            get
            {
                if ((this.mUIBtnBuscarWindow == null))
                {
                    this.mUIBtnBuscarWindow = new UIBtnBuscarWindow(this);
                }
                return this.mUIBtnBuscarWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIGestionClientesWindow mUIGestionClientesWindow;
        
        private UIBtnRegistrarWindow mUIBtnRegistrarWindow;
        
        private UIBtnBuscarWindow mUIBtnBuscarWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIGestionClientesWindow : WinWindow
    {
        
        public UIGestionClientesWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "Label";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinText UIGestionClientesText
        {
            get
            {
                if ((this.mUIGestionClientesText == null))
                {
                    this.mUIGestionClientesText = new WinText(this);
                    #region Criterio de búsqueda
                    this.mUIGestionClientesText.SearchProperties[WinText.PropertyNames.Name] = "Gestion Clientes";
                    this.mUIGestionClientesText.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIGestionClientesText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIGestionClientesText;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIBtnRegistrarWindow : WinWindow
    {
        
        public UIBtnRegistrarWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnRegistrar";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinClient UIBtnRegistrarClient
        {
            get
            {
                if ((this.mUIBtnRegistrarClient == null))
                {
                    this.mUIBtnRegistrarClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUIBtnRegistrarClient.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIBtnRegistrarClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIBtnRegistrarClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIBtnBuscarWindow : WinWindow
    {
        
        public UIBtnBuscarWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnBuscar";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinClient UIBtnBuscarClient
        {
            get
            {
                if ((this.mUIBtnBuscarClient == null))
                {
                    this.mUIBtnBuscarClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUIBtnBuscarClient.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIBtnBuscarClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIBtnBuscarClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIViewRegistroClienteWindow : WinWindow
    {
        
        public UIViewRegistroClienteWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "ViewRegistroCliente";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("ViewRegistroCliente");
            #endregion
        }
        
        #region Properties
        public UIEntertextWindow2 UIEntertextWindow
        {
            get
            {
                if ((this.mUIEntertextWindow == null))
                {
                    this.mUIEntertextWindow = new UIEntertextWindow2(this);
                }
                return this.mUIEntertextWindow;
            }
        }
        
        public UITxtNombreWindow UITxtNombreWindow
        {
            get
            {
                if ((this.mUITxtNombreWindow == null))
                {
                    this.mUITxtNombreWindow = new UITxtNombreWindow(this);
                }
                return this.mUITxtNombreWindow;
            }
        }
        
        public UIEntertextWindow11 UIEntertextWindow1
        {
            get
            {
                if ((this.mUIEntertextWindow1 == null))
                {
                    this.mUIEntertextWindow1 = new UIEntertextWindow11(this);
                }
                return this.mUIEntertextWindow1;
            }
        }
        
        public UITxtApellidoWindow UITxtApellidoWindow
        {
            get
            {
                if ((this.mUITxtApellidoWindow == null))
                {
                    this.mUITxtApellidoWindow = new UITxtApellidoWindow(this);
                }
                return this.mUITxtApellidoWindow;
            }
        }
        
        public UIEntertextWindow21 UIEntertextWindow2
        {
            get
            {
                if ((this.mUIEntertextWindow2 == null))
                {
                    this.mUIEntertextWindow2 = new UIEntertextWindow21(this);
                }
                return this.mUIEntertextWindow2;
            }
        }
        
        public UITxtDireccionWindow UITxtDireccionWindow
        {
            get
            {
                if ((this.mUITxtDireccionWindow == null))
                {
                    this.mUITxtDireccionWindow = new UITxtDireccionWindow(this);
                }
                return this.mUITxtDireccionWindow;
            }
        }
        
        public UIEntertextWindow3 UIEntertextWindow3
        {
            get
            {
                if ((this.mUIEntertextWindow3 == null))
                {
                    this.mUIEntertextWindow3 = new UIEntertextWindow3(this);
                }
                return this.mUIEntertextWindow3;
            }
        }
        
        public UIEntertextWindow4 UIEntertextWindow4
        {
            get
            {
                if ((this.mUIEntertextWindow4 == null))
                {
                    this.mUIEntertextWindow4 = new UIEntertextWindow4(this);
                }
                return this.mUIEntertextWindow4;
            }
        }
        
        public WinClient UIViewRegistroClienteClient
        {
            get
            {
                if ((this.mUIViewRegistroClienteClient == null))
                {
                    this.mUIViewRegistroClienteClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUIViewRegistroClienteClient.SearchProperties[WinControl.PropertyNames.Name] = "ViewRegistroCliente";
                    this.mUIViewRegistroClienteClient.WindowTitles.Add("ViewRegistroCliente");
                    #endregion
                }
                return this.mUIViewRegistroClienteClient;
            }
        }
        
        public UITxtTelefonoWindow UITxtTelefonoWindow
        {
            get
            {
                if ((this.mUITxtTelefonoWindow == null))
                {
                    this.mUITxtTelefonoWindow = new UITxtTelefonoWindow(this);
                }
                return this.mUITxtTelefonoWindow;
            }
        }
        
        public UIEntertextWindow5 UIEntertextWindow5
        {
            get
            {
                if ((this.mUIEntertextWindow5 == null))
                {
                    this.mUIEntertextWindow5 = new UIEntertextWindow5(this);
                }
                return this.mUIEntertextWindow5;
            }
        }
        
        public UIEntertextWindow6 UIEntertextWindow6
        {
            get
            {
                if ((this.mUIEntertextWindow6 == null))
                {
                    this.mUIEntertextWindow6 = new UIEntertextWindow6(this);
                }
                return this.mUIEntertextWindow6;
            }
        }
        
        public UIRegistrarWindow UIRegistrarWindow
        {
            get
            {
                if ((this.mUIRegistrarWindow == null))
                {
                    this.mUIRegistrarWindow = new UIRegistrarWindow(this);
                }
                return this.mUIRegistrarWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIEntertextWindow2 mUIEntertextWindow;
        
        private UITxtNombreWindow mUITxtNombreWindow;
        
        private UIEntertextWindow11 mUIEntertextWindow1;
        
        private UITxtApellidoWindow mUITxtApellidoWindow;
        
        private UIEntertextWindow21 mUIEntertextWindow2;
        
        private UITxtDireccionWindow mUITxtDireccionWindow;
        
        private UIEntertextWindow3 mUIEntertextWindow3;
        
        private UIEntertextWindow4 mUIEntertextWindow4;
        
        private WinClient mUIViewRegistroClienteClient;
        
        private UITxtTelefonoWindow mUITxtTelefonoWindow;
        
        private UIEntertextWindow5 mUIEntertextWindow5;
        
        private UIEntertextWindow6 mUIEntertextWindow6;
        
        private UIRegistrarWindow mUIRegistrarWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow2 : WinWindow
    {
        
        public UIEntertextWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "7";
            this.WindowTitles.Add("ViewRegistroCliente");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroCliente");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UITxtNombreWindow : WinWindow
    {
        
        public UITxtNombreWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtNombre";
            this.WindowTitles.Add("ViewRegistroCliente");
            #endregion
        }
        
        #region Properties
        public WinClient UITxtNombreClient
        {
            get
            {
                if ((this.mUITxtNombreClient == null))
                {
                    this.mUITxtNombreClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUITxtNombreClient.WindowTitles.Add("ViewRegistroCliente");
                    #endregion
                }
                return this.mUITxtNombreClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUITxtNombreClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow11 : WinWindow
    {
        
        public UIEntertextWindow11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "6";
            this.WindowTitles.Add("ViewRegistroCliente");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroCliente");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UITxtApellidoWindow : WinWindow
    {
        
        public UITxtApellidoWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtApellido";
            this.WindowTitles.Add("ViewRegistroCliente");
            #endregion
        }
        
        #region Properties
        public WinClient UITxtApellidoClient
        {
            get
            {
                if ((this.mUITxtApellidoClient == null))
                {
                    this.mUITxtApellidoClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUITxtApellidoClient.WindowTitles.Add("ViewRegistroCliente");
                    #endregion
                }
                return this.mUITxtApellidoClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUITxtApellidoClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow21 : WinWindow
    {
        
        public UIEntertextWindow21(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "5";
            this.WindowTitles.Add("ViewRegistroCliente");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroCliente");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UITxtDireccionWindow : WinWindow
    {
        
        public UITxtDireccionWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtDireccion";
            this.WindowTitles.Add("ViewRegistroCliente");
            #endregion
        }
        
        #region Properties
        public WinClient UITxtDireccionClient
        {
            get
            {
                if ((this.mUITxtDireccionClient == null))
                {
                    this.mUITxtDireccionClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUITxtDireccionClient.WindowTitles.Add("ViewRegistroCliente");
                    #endregion
                }
                return this.mUITxtDireccionClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUITxtDireccionClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow3 : WinWindow
    {
        
        public UIEntertextWindow3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "4";
            this.WindowTitles.Add("ViewRegistroCliente");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroCliente");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow4 : WinWindow
    {
        
        public UIEntertextWindow4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "3";
            this.WindowTitles.Add("ViewRegistroCliente");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroCliente");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UITxtTelefonoWindow : WinWindow
    {
        
        public UITxtTelefonoWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtTelefono";
            this.WindowTitles.Add("ViewRegistroCliente");
            #endregion
        }
        
        #region Properties
        public WinClient UITxtTelefonoClient
        {
            get
            {
                if ((this.mUITxtTelefonoClient == null))
                {
                    this.mUITxtTelefonoClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUITxtTelefonoClient.WindowTitles.Add("ViewRegistroCliente");
                    #endregion
                }
                return this.mUITxtTelefonoClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUITxtTelefonoClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow5 : WinWindow
    {
        
        public UIEntertextWindow5(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("ViewRegistroCliente");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroCliente");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow6 : WinWindow
    {
        
        public UIEntertextWindow6(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.WindowTitles.Add("ViewRegistroCliente");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroCliente");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIRegistrarWindow : WinWindow
    {
        
        public UIRegistrarWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "Label";
            this.WindowTitles.Add("ViewRegistroCliente");
            #endregion
        }
        
        #region Properties
        public WinText UIRegistrarText
        {
            get
            {
                if ((this.mUIRegistrarText == null))
                {
                    this.mUIRegistrarText = new WinText(this);
                    #region Criterio de búsqueda
                    this.mUIRegistrarText.SearchProperties[WinText.PropertyNames.Name] = "Registrar";
                    this.mUIRegistrarText.WindowTitles.Add("ViewRegistroCliente");
                    #endregion
                }
                return this.mUIRegistrarText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIRegistrarText;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIConfirmacionWindow : WinWindow
    {
        
        public UIConfirmacionWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Confirmacion";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Confirmacion");
            #endregion
        }
        
        #region Properties
        public UIOKWindow1 UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow1(this);
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIOKWindow1 mUIOKWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIOKWindow1 : WinWindow
    {
        
        public UIOKWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "2";
            this.WindowTitles.Add("Confirmacion");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Criterio de búsqueda
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("Confirmacion");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
}
