

USE SIVET 
GO

CREATE OR ALTER TRIGGER DP_RESERVAMATERIALES ON Detalles_Pedido AFTER INSERT
AS
	BEGIN
		set nocount on

		DECLARE @ID_MATERIAL NUMERIC(6)
		DECLARE @CANTIDAD NUMERIC(6)

		SELECT @ID_MATERIAL=I.Id_Material,@CANTIDAD=Cantidad
		FROM inserted I

		DECLARE @EXISTENCIA NUMERIC(6) 
		DECLARE @COPY_2 NUMERIC(6)

		SET @EXISTENCIA =(SELECT M.Stock FROM Materiales M WHERE M.Id_Material=@ID_MATERIAL)

		UPDATE Materiales
		SET Stock = @EXISTENCIA - @CANTIDAD
		WHERE Id_Material=@ID_MATERIAL
	END
GO

CREATE OR ALTER TRIGGER LV_ACTUALIZA ON Materiales INSTEAD OF UPDATE
AS
	BEGIN

		set nocount on

		DECLARE @ID_MATERIAL INT
		DECLARE @CANTIDAD_A INT
		DECLARE @CANTIDAD_D INT
		DECLARE @PORCENTAJE NUMERIC(5,2)
		DECLARE @ID_LIMITEVENTA INT

		SELECT @ID_MATERIAL=I.Id_Material,@CANTIDAD_A=I.Stock
		FROM inserted I

		SELECT @CANTIDAD_D=M.Stock,@PORCENTAJE=LV.Porcentaje,@ID_LIMITEVENTA=LV.Id_LimitesVenta
		FROM Materiales M
		JOIN LimitesVenta LV
		ON LV.Id_LimitesVenta=M.Id_LimitesVenta
		WHERE M.Id_Material=@ID_MATERIAL

		UPDATE Materiales
		SET Stock = @CANTIDAD_A
		WHERE Id_Material=@ID_MATERIAL

		DECLARE @PORCENTAJE_C NUMERIC(10,2)

		SET @PORCENTAJE_C=@PORCENTAJE*@CANTIDAD_A/@CANTIDAD_D

		IF(@PORCENTAJE_C>100)
		BEGIN
			UPDATE LimitesVenta
			SET Porcentaje= 100,
			FechaUltimoCambio=GETDATE()
			WHERE Id_LimitesVenta=@ID_LIMITEVENTA
		END
		ELSE IF(@PORCENTAJE_C BETWEEN 0 AND 100)
		BEGIN
			UPDATE LimitesVenta
			SET Porcentaje= @PORCENTAJE_C,
			FechaUltimoCambio=GETDATE()
			WHERE Id_LimitesVenta=@ID_LIMITEVENTA
		END

		ELSE IF(@PORCENTAJE_C < 0)
		BEGIN
			UPDATE LimitesVenta
			SET Porcentaje= 0,
			FechaUltimoCambio=GETDATE()
			WHERE Id_LimitesVenta=@ID_LIMITEVENTA
		END
	END
GO
