// ------------------------------------------------------------------------------
//  <auto-generated>
//      Este código lo generó el generador de pruebas automatizadas de IU.
//      Versión: 16.0.0.0
//
//      Los cambios realizados en este archivo pueden provocar un comportamiento incorrecto y se perderán si
//      se vuelve a generar el código.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITest_Gestion_Empleado
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Gestion Empleados
        /// </summary>
        public void RecordedMethod()
        {
            #region Variable Declarations
            WinEdit uIEditEdit = this.UIViewLogWindow.UIEntertextWindow.UIEditEdit;
            WinWindow uIEntertextWindow = this.UIViewLogWindow.UITxt2Window.UIEntertextWindow;
            WinEdit uIEditEdit1 = this.UIViewLogWindow.UIEntertextWindow1.UIEditEdit;
            WinClient uIIniciarSesionClient = this.UIViewLogWindow.UIBtnIniciarSesionWindow.UIIniciarSesionClient;
            WinControl uIItemDialog = this.UIItemWindow.UIItemWindow1.UIItemDialog;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            WinText uIGestionEmpleadoText = this.UIViewPrincipalWindow.UIGestionEmpleadoWindow.UIGestionEmpleadoText;
            WinClient uIBtnRegistrarClient = this.UIViewPrincipalWindow.UIBtnRegistrarWindow.UIBtnRegistrarClient;
            WinEdit uIEditEdit2 = this.UIViewRegistroEmpleadoWindow.UIEntertextWindow.UIEditEdit;
            WinClient uIViewRegistroEmpleadoClient = this.UIViewRegistroEmpleadoWindow.UIViewRegistroEmpleadoClient;
            WinEdit uIEditEdit3 = this.UIViewRegistroEmpleadoWindow.UIEntertextWindow1.UIEditEdit;
            WinClient uITxtApellidoClient = this.UIViewRegistroEmpleadoWindow.UITxtApellidoWindow.UITxtApellidoClient;
            WinEdit uIEditEdit4 = this.UIViewRegistroEmpleadoWindow.UIEntertextWindow2.UIEditEdit;
            WinEdit uIEditEdit5 = this.UIViewRegistroEmpleadoWindow.UIEntertextWindow3.UIEditEdit;
            WinClient uITxtCargoClient = this.UIViewRegistroEmpleadoWindow.UITxtCargoWindow.UITxtCargoClient;
            WinEdit uIEditEdit6 = this.UIViewRegistroEmpleadoWindow.UIEntertextWindow4.UIEditEdit;
            WinEdit uIEditEdit7 = this.UIViewRegistroEmpleadoWindow.UIEntertextWindow5.UIEditEdit;
            WinEdit uIEditEdit8 = this.UIViewRegistroEmpleadoWindow.UIEntertextWindow6.UIEditEdit;
            WinClient uITxtTelefonoClient = this.UIViewRegistroEmpleadoWindow.UITxtTelefonoWindow.UITxtTelefonoClient;
            WinEdit uIEditEdit9 = this.UIViewRegistroEmpleadoWindow.UIEntertextWindow7.UIEditEdit;
            WinEdit uIEditEdit10 = this.UIViewRegistroEmpleadoWindow.UIEntertextWindow8.UIEditEdit;
            WinText uIRegistrarText = this.UIViewRegistroEmpleadoWindow.UIRegistrarWindow.UIRegistrarText;
            WinButton uIOKButton1 = this.UIConfirmacionWindow.UIOKWindow.UIOKButton;
            WinClient uIBtnBuscarClient = this.UIViewPrincipalWindow.UIBtnBuscarWindow.UIBtnBuscarClient;
            WinColumnHeader uIIDEmpleadoColumnHeader = this.UIViewPrincipalWindow.UIDgvEmpleadosWindow.UIDataGridViewTable.UITopRowRow.UIIDEmpleadoColumnHeader;
            WinButton uICloseButton = this.UIViewPrincipalWindow.UIViewPrincipalTitleBar.UICloseButton;
            #endregion

            // Iniciar '%USERPROFILE%\Downloads\DDD (1)\DDD\UI.Desktop\bin\Debug\UI.Desktop.exe'
            ApplicationUnderTest uIViewLogWindow = ApplicationUnderTest.Launch(this.RecordedMethodParams.UIViewLogWindowExePath, this.RecordedMethodParams.UIViewLogWindowAlternateExePath);

            // Escribir 'Admin' en cuadro de texto 'edit'
            uIEditEdit.Text = this.RecordedMethodParams.UIEditEditText;


            // Escribir '123qweu0' en cuadro de texto 'edit'
            uIEditEdit1.Text = this.RecordedMethodParams.UIEditEditText1;

            // Clic 'Iniciar Sesion' cliente
            Mouse.Click(uIIniciarSesionClient, new Point(94, 10));

            // Clic Dialog
            Mouse.Click(uIItemDialog, new Point(109, 83));

            // Clic 'OK' botón
            Mouse.Click(uIOKButton, new Point(73, 11));

            // Clic 'Gestion Empleado' etiqueta
            Mouse.Click(uIGestionEmpleadoText, new Point(15, 4));

            // Clic 'btnRegistrar' cliente
            Mouse.Click(uIBtnRegistrarClient, new Point(27, 21));

            // Escribir '9988' en cuadro de texto 'edit'
            uIEditEdit2.Text = this.RecordedMethodParams.UIEditEditText2;

            // Clic 'ViewRegistroEmpleado' cliente
            Mouse.Click(uIViewRegistroEmpleadoClient, new Point(225, 162));

            // Escribir 'Jhonatan' en cuadro de texto 'edit'
            uIEditEdit3.Text = this.RecordedMethodParams.UIEditEditText3;

            // Clic 'txtApellido' cliente
            Mouse.Click(uITxtApellidoClient, new Point(97, 8));

            // Escribir 'Ramos' en cuadro de texto 'edit'
            uIEditEdit4.Text = this.RecordedMethodParams.UIEditEditText4;

            // Escribir 'Encargado de Almacen' en cuadro de texto 'edit'
            uIEditEdit5.Text = this.RecordedMethodParams.UIEditEditText5;

            // Clic 'txtCargo' cliente
            Mouse.Click(uITxtCargoClient, new Point(67, 32));

            // Escribir 'Almacen' en cuadro de texto 'edit'
            uIEditEdit6.Text = this.RecordedMethodParams.UIEditEditText6;

            // Escribir 'TAcna' en cuadro de texto 'edit'
            uIEditEdit7.Text = this.RecordedMethodParams.UIEditEditText7;

            // Escribir 'Jhontana2021' en cuadro de texto 'edit'
            uIEditEdit8.Text = this.RecordedMethodParams.UIEditEditText8;

            // Clic 'txtTelefono' cliente
            Mouse.Click(uITxtTelefonoClient, new Point(104, 34));

            // Escribir '123' en cuadro de texto 'edit'
            uIEditEdit9.Text = this.RecordedMethodParams.UIEditEditText9;

            // Clic 'edit' cuadro de texto
            Mouse.Click(uIEditEdit10, new Point(87, 10));

            // Escribir '********' en cuadro de texto 'edit'
            Keyboard.SendKeys(uIEditEdit10, this.RecordedMethodParams.UIEditEditSendKeys, true);

            // Clic 'Registrar' etiqueta
            Mouse.Click(uIRegistrarText, new Point(23, 9));

            // Clic 'OK' botón
            Mouse.Click(uIOKButton1, new Point(27, 11));

            // Clic 'btnBuscar' cliente
            Mouse.Click(uIBtnBuscarClient, new Point(19, 15));

            // Clic 'ID Empleado' encabezado de columna
            Mouse.Click(uIIDEmpleadoColumnHeader, new Point(79, 23));

            // Clic 'ID Empleado' encabezado de columna
            Mouse.Click(uIIDEmpleadoColumnHeader, new Point(79, 23));

            // Clic 'Close' botón
            Mouse.Click(uICloseButton, new Point(20, 14));
        }
        
        #region Properties
        public virtual RecordedMethodParams RecordedMethodParams
        {
            get
            {
                if ((this.mRecordedMethodParams == null))
                {
                    this.mRecordedMethodParams = new RecordedMethodParams();
                }
                return this.mRecordedMethodParams;
            }
        }
        
        public UIViewLogWindow UIViewLogWindow
        {
            get
            {
                if ((this.mUIViewLogWindow == null))
                {
                    this.mUIViewLogWindow = new UIViewLogWindow();
                }
                return this.mUIViewLogWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow();
                }
                return this.mUIOKWindow;
            }
        }
        
        public UIViewPrincipalWindow UIViewPrincipalWindow
        {
            get
            {
                if ((this.mUIViewPrincipalWindow == null))
                {
                    this.mUIViewPrincipalWindow = new UIViewPrincipalWindow();
                }
                return this.mUIViewPrincipalWindow;
            }
        }
        
        public UIViewRegistroEmpleadoWindow UIViewRegistroEmpleadoWindow
        {
            get
            {
                if ((this.mUIViewRegistroEmpleadoWindow == null))
                {
                    this.mUIViewRegistroEmpleadoWindow = new UIViewRegistroEmpleadoWindow();
                }
                return this.mUIViewRegistroEmpleadoWindow;
            }
        }
        
        public UIConfirmacionWindow UIConfirmacionWindow
        {
            get
            {
                if ((this.mUIConfirmacionWindow == null))
                {
                    this.mUIConfirmacionWindow = new UIConfirmacionWindow();
                }
                return this.mUIConfirmacionWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethodParams mRecordedMethodParams;
        
        private UIViewLogWindow mUIViewLogWindow;
        
        private UIItemWindow mUIItemWindow;
        
        private UIOKWindow mUIOKWindow;
        
        private UIViewPrincipalWindow mUIViewPrincipalWindow;
        
        private UIViewRegistroEmpleadoWindow mUIViewRegistroEmpleadoWindow;
        
        private UIConfirmacionWindow mUIConfirmacionWindow;
        #endregion
    }
    
    /// <summary>
    /// Parámetros que se van a pasar a 'RecordedMethod'
    /// </summary>
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class RecordedMethodParams
    {
        
        #region Fields
        /// <summary>
        /// Iniciar '%USERPROFILE%\Downloads\DDD (1)\DDD\UI.Desktop\bin\Debug\UI.Desktop.exe'
        /// </summary>
        public string UIViewLogWindowExePath = "C:\\Users\\USUARIO\\Downloads\\DDD (1)\\DDD\\UI.Desktop\\bin\\Debug\\UI.Desktop.exe";
        
        /// <summary>
        /// Iniciar '%USERPROFILE%\Downloads\DDD (1)\DDD\UI.Desktop\bin\Debug\UI.Desktop.exe'
        /// </summary>
        public string UIViewLogWindowAlternateExePath = "%USERPROFILE%\\Downloads\\DDD (1)\\DDD\\UI.Desktop\\bin\\Debug\\UI.Desktop.exe";
        
        /// <summary>
        /// Escribir 'Admin' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText = "Admin";
        
        /// <summary>
        /// Escribir '123qweu0' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText1 = "123qweu0";
        
        /// <summary>
        /// Escribir '9988' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText2 = "9988";
        
        /// <summary>
        /// Escribir 'Jhonatan' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText3 = "Jhonatan";
        
        /// <summary>
        /// Escribir 'Ramos' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText4 = "Ramos";
        
        /// <summary>
        /// Escribir 'Encargado de Almacen' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText5 = "Encargado de Almacen";
        
        /// <summary>
        /// Escribir 'Almacen' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText6 = "Almacen";
        
        /// <summary>
        /// Escribir 'TAcna' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText7 = "TAcna";
        
        /// <summary>
        /// Escribir 'Jhontana2021' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText8 = "Jhontana2021";
        
        /// <summary>
        /// Escribir '123' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText9 = "123";
        
        /// <summary>
        /// Escribir '********' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditSendKeys = "mOL/lXDUSd/hy7K5BZnJEA==";
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIViewLogWindow : WinWindow
    {
        
        public UIViewLogWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "ViewLog";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.FilterProperties[WinWindow.PropertyNames.OrderOfInvocation] = "2";
            this.WindowTitles.Add("ViewLog");
            #endregion
        }
        
        #region Properties
        public UIEntertextWindow UIEntertextWindow
        {
            get
            {
                if ((this.mUIEntertextWindow == null))
                {
                    this.mUIEntertextWindow = new UIEntertextWindow(this);
                }
                return this.mUIEntertextWindow;
            }
        }
        
        public UITxt2Window UITxt2Window
        {
            get
            {
                if ((this.mUITxt2Window == null))
                {
                    this.mUITxt2Window = new UITxt2Window(this);
                }
                return this.mUITxt2Window;
            }
        }
        
        public UIEntertextWindow1 UIEntertextWindow1
        {
            get
            {
                if ((this.mUIEntertextWindow1 == null))
                {
                    this.mUIEntertextWindow1 = new UIEntertextWindow1(this);
                }
                return this.mUIEntertextWindow1;
            }
        }
        
        public UIBtnIniciarSesionWindow UIBtnIniciarSesionWindow
        {
            get
            {
                if ((this.mUIBtnIniciarSesionWindow == null))
                {
                    this.mUIBtnIniciarSesionWindow = new UIBtnIniciarSesionWindow(this);
                }
                return this.mUIBtnIniciarSesionWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIEntertextWindow mUIEntertextWindow;
        
        private UITxt2Window mUITxt2Window;
        
        private UIEntertextWindow1 mUIEntertextWindow1;
        
        private UIBtnIniciarSesionWindow mUIBtnIniciarSesionWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow : WinWindow
    {
        
        public UIEntertextWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("ViewLog");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewLog");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UITxt2Window : WinWindow
    {
        
        public UITxt2Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txt2";
            this.WindowTitles.Add("ViewLog");
            #endregion
        }
        
        #region Properties
        public WinWindow UIEntertextWindow
        {
            get
            {
                if ((this.mUIEntertextWindow == null))
                {
                    this.mUIEntertextWindow = new WinWindow(this);
                    #region Criterio de búsqueda
                    this.mUIEntertextWindow.SearchProperties[WinWindow.PropertyNames.Name] = "Enter text";
                    this.mUIEntertextWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUIEntertextWindow.WindowTitles.Add("ViewLog");
                    #endregion
                }
                return this.mUIEntertextWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIEntertextWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow1 : WinWindow
    {
        
        public UIEntertextWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.WindowTitles.Add("ViewLog");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewLog");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIBtnIniciarSesionWindow : WinWindow
    {
        
        public UIBtnIniciarSesionWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnIniciarSesion";
            this.WindowTitles.Add("ViewLog");
            #endregion
        }
        
        #region Properties
        public WinClient UIIniciarSesionClient
        {
            get
            {
                if ((this.mUIIniciarSesionClient == null))
                {
                    this.mUIIniciarSesionClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUIIniciarSesionClient.SearchProperties[WinControl.PropertyNames.Name] = "Iniciar Sesion";
                    this.mUIIniciarSesionClient.WindowTitles.Add("ViewLog");
                    #endregion
                }
                return this.mUIIniciarSesionClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIIniciarSesionClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Desktop 1";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32769";
            #endregion
        }
        
        #region Properties
        public UIItemWindow1 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow1(this);
                }
                return this.mUIItemWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow1 mUIItemWindow1;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            #endregion
        }
        
        #region Properties
        public WinControl UIItemDialog
        {
            get
            {
                if ((this.mUIItemDialog == null))
                {
                    this.mUIItemDialog = new WinControl(this);
                    #region Criterio de búsqueda
                    this.mUIItemDialog.SearchProperties[UITestControl.PropertyNames.ControlType] = "Dialog";
                    #endregion
                }
                return this.mUIItemDialog;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIItemDialog;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "OK";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Button";
            this.WindowTitles.Add("OK");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Criterio de búsqueda
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("OK");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIViewPrincipalWindow : WinWindow
    {
        
        public UIViewPrincipalWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "ViewPrincipal";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public UIGestionEmpleadoWindow UIGestionEmpleadoWindow
        {
            get
            {
                if ((this.mUIGestionEmpleadoWindow == null))
                {
                    this.mUIGestionEmpleadoWindow = new UIGestionEmpleadoWindow(this);
                }
                return this.mUIGestionEmpleadoWindow;
            }
        }
        
        public UIBtnRegistrarWindow UIBtnRegistrarWindow
        {
            get
            {
                if ((this.mUIBtnRegistrarWindow == null))
                {
                    this.mUIBtnRegistrarWindow = new UIBtnRegistrarWindow(this);
                }
                return this.mUIBtnRegistrarWindow;
            }
        }
        
        public UIBtnBuscarWindow UIBtnBuscarWindow
        {
            get
            {
                if ((this.mUIBtnBuscarWindow == null))
                {
                    this.mUIBtnBuscarWindow = new UIBtnBuscarWindow(this);
                }
                return this.mUIBtnBuscarWindow;
            }
        }
        
        public UIDgvEmpleadosWindow UIDgvEmpleadosWindow
        {
            get
            {
                if ((this.mUIDgvEmpleadosWindow == null))
                {
                    this.mUIDgvEmpleadosWindow = new UIDgvEmpleadosWindow(this);
                }
                return this.mUIDgvEmpleadosWindow;
            }
        }
        
        public UIViewPrincipalTitleBar UIViewPrincipalTitleBar
        {
            get
            {
                if ((this.mUIViewPrincipalTitleBar == null))
                {
                    this.mUIViewPrincipalTitleBar = new UIViewPrincipalTitleBar(this);
                }
                return this.mUIViewPrincipalTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIGestionEmpleadoWindow mUIGestionEmpleadoWindow;
        
        private UIBtnRegistrarWindow mUIBtnRegistrarWindow;
        
        private UIBtnBuscarWindow mUIBtnBuscarWindow;
        
        private UIDgvEmpleadosWindow mUIDgvEmpleadosWindow;
        
        private UIViewPrincipalTitleBar mUIViewPrincipalTitleBar;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIGestionEmpleadoWindow : WinWindow
    {
        
        public UIGestionEmpleadoWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "Label";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinText UIGestionEmpleadoText
        {
            get
            {
                if ((this.mUIGestionEmpleadoText == null))
                {
                    this.mUIGestionEmpleadoText = new WinText(this);
                    #region Criterio de búsqueda
                    this.mUIGestionEmpleadoText.SearchProperties[WinText.PropertyNames.Name] = "Gestion Empleado";
                    this.mUIGestionEmpleadoText.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIGestionEmpleadoText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIGestionEmpleadoText;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIBtnRegistrarWindow : WinWindow
    {
        
        public UIBtnRegistrarWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnRegistrar";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinClient UIBtnRegistrarClient
        {
            get
            {
                if ((this.mUIBtnRegistrarClient == null))
                {
                    this.mUIBtnRegistrarClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUIBtnRegistrarClient.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIBtnRegistrarClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIBtnRegistrarClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIBtnBuscarWindow : WinWindow
    {
        
        public UIBtnBuscarWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnBuscar";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinClient UIBtnBuscarClient
        {
            get
            {
                if ((this.mUIBtnBuscarClient == null))
                {
                    this.mUIBtnBuscarClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUIBtnBuscarClient.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIBtnBuscarClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIBtnBuscarClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIDgvEmpleadosWindow : WinWindow
    {
        
        public UIDgvEmpleadosWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "dgvEmpleados";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public UIDataGridViewTable UIDataGridViewTable
        {
            get
            {
                if ((this.mUIDataGridViewTable == null))
                {
                    this.mUIDataGridViewTable = new UIDataGridViewTable(this);
                }
                return this.mUIDataGridViewTable;
            }
        }
        #endregion
        
        #region Fields
        private UIDataGridViewTable mUIDataGridViewTable;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIDataGridViewTable : WinTable
    {
        
        public UIDataGridViewTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinTable.PropertyNames.Name] = "DataGridView";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public UITopRowRow UITopRowRow
        {
            get
            {
                if ((this.mUITopRowRow == null))
                {
                    this.mUITopRowRow = new UITopRowRow(this);
                }
                return this.mUITopRowRow;
            }
        }
        #endregion
        
        #region Fields
        private UITopRowRow mUITopRowRow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UITopRowRow : WinRow
    {
        
        public UITopRowRow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinRow.PropertyNames.Name] = "Top Row";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinColumnHeader UIIDEmpleadoColumnHeader
        {
            get
            {
                if ((this.mUIIDEmpleadoColumnHeader == null))
                {
                    this.mUIIDEmpleadoColumnHeader = new WinColumnHeader(this);
                    #region Criterio de búsqueda
                    this.mUIIDEmpleadoColumnHeader.SearchProperties[WinControl.PropertyNames.Name] = "ID Empleado";
                    this.mUIIDEmpleadoColumnHeader.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIIDEmpleadoColumnHeader;
            }
        }
        #endregion
        
        #region Fields
        private WinColumnHeader mUIIDEmpleadoColumnHeader;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIViewPrincipalTitleBar : WinTitleBar
    {
        
        public UIViewPrincipalTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Criterio de búsqueda
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIViewRegistroEmpleadoWindow : WinWindow
    {
        
        public UIViewRegistroEmpleadoWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "ViewRegistroEmpleado";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public UIEntertextWindow2 UIEntertextWindow
        {
            get
            {
                if ((this.mUIEntertextWindow == null))
                {
                    this.mUIEntertextWindow = new UIEntertextWindow2(this);
                }
                return this.mUIEntertextWindow;
            }
        }
        
        public WinClient UIViewRegistroEmpleadoClient
        {
            get
            {
                if ((this.mUIViewRegistroEmpleadoClient == null))
                {
                    this.mUIViewRegistroEmpleadoClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUIViewRegistroEmpleadoClient.SearchProperties[WinControl.PropertyNames.Name] = "ViewRegistroEmpleado";
                    this.mUIViewRegistroEmpleadoClient.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUIViewRegistroEmpleadoClient;
            }
        }
        
        public UIEntertextWindow11 UIEntertextWindow1
        {
            get
            {
                if ((this.mUIEntertextWindow1 == null))
                {
                    this.mUIEntertextWindow1 = new UIEntertextWindow11(this);
                }
                return this.mUIEntertextWindow1;
            }
        }
        
        public UITxtApellidoWindow UITxtApellidoWindow
        {
            get
            {
                if ((this.mUITxtApellidoWindow == null))
                {
                    this.mUITxtApellidoWindow = new UITxtApellidoWindow(this);
                }
                return this.mUITxtApellidoWindow;
            }
        }
        
        public UIEntertextWindow21 UIEntertextWindow2
        {
            get
            {
                if ((this.mUIEntertextWindow2 == null))
                {
                    this.mUIEntertextWindow2 = new UIEntertextWindow21(this);
                }
                return this.mUIEntertextWindow2;
            }
        }
        
        public UIEntertextWindow3 UIEntertextWindow3
        {
            get
            {
                if ((this.mUIEntertextWindow3 == null))
                {
                    this.mUIEntertextWindow3 = new UIEntertextWindow3(this);
                }
                return this.mUIEntertextWindow3;
            }
        }
        
        public UITxtCargoWindow UITxtCargoWindow
        {
            get
            {
                if ((this.mUITxtCargoWindow == null))
                {
                    this.mUITxtCargoWindow = new UITxtCargoWindow(this);
                }
                return this.mUITxtCargoWindow;
            }
        }
        
        public UIEntertextWindow4 UIEntertextWindow4
        {
            get
            {
                if ((this.mUIEntertextWindow4 == null))
                {
                    this.mUIEntertextWindow4 = new UIEntertextWindow4(this);
                }
                return this.mUIEntertextWindow4;
            }
        }
        
        public UIEntertextWindow5 UIEntertextWindow5
        {
            get
            {
                if ((this.mUIEntertextWindow5 == null))
                {
                    this.mUIEntertextWindow5 = new UIEntertextWindow5(this);
                }
                return this.mUIEntertextWindow5;
            }
        }
        
        public UIEntertextWindow6 UIEntertextWindow6
        {
            get
            {
                if ((this.mUIEntertextWindow6 == null))
                {
                    this.mUIEntertextWindow6 = new UIEntertextWindow6(this);
                }
                return this.mUIEntertextWindow6;
            }
        }
        
        public UITxtTelefonoWindow UITxtTelefonoWindow
        {
            get
            {
                if ((this.mUITxtTelefonoWindow == null))
                {
                    this.mUITxtTelefonoWindow = new UITxtTelefonoWindow(this);
                }
                return this.mUITxtTelefonoWindow;
            }
        }
        
        public UIEntertextWindow7 UIEntertextWindow7
        {
            get
            {
                if ((this.mUIEntertextWindow7 == null))
                {
                    this.mUIEntertextWindow7 = new UIEntertextWindow7(this);
                }
                return this.mUIEntertextWindow7;
            }
        }
        
        public UIEntertextWindow8 UIEntertextWindow8
        {
            get
            {
                if ((this.mUIEntertextWindow8 == null))
                {
                    this.mUIEntertextWindow8 = new UIEntertextWindow8(this);
                }
                return this.mUIEntertextWindow8;
            }
        }
        
        public UIRegistrarWindow UIRegistrarWindow
        {
            get
            {
                if ((this.mUIRegistrarWindow == null))
                {
                    this.mUIRegistrarWindow = new UIRegistrarWindow(this);
                }
                return this.mUIRegistrarWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIEntertextWindow2 mUIEntertextWindow;
        
        private WinClient mUIViewRegistroEmpleadoClient;
        
        private UIEntertextWindow11 mUIEntertextWindow1;
        
        private UITxtApellidoWindow mUITxtApellidoWindow;
        
        private UIEntertextWindow21 mUIEntertextWindow2;
        
        private UIEntertextWindow3 mUIEntertextWindow3;
        
        private UITxtCargoWindow mUITxtCargoWindow;
        
        private UIEntertextWindow4 mUIEntertextWindow4;
        
        private UIEntertextWindow5 mUIEntertextWindow5;
        
        private UIEntertextWindow6 mUIEntertextWindow6;
        
        private UITxtTelefonoWindow mUITxtTelefonoWindow;
        
        private UIEntertextWindow7 mUIEntertextWindow7;
        
        private UIEntertextWindow8 mUIEntertextWindow8;
        
        private UIRegistrarWindow mUIRegistrarWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow2 : WinWindow
    {
        
        public UIEntertextWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "9";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow11 : WinWindow
    {
        
        public UIEntertextWindow11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "8";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UITxtApellidoWindow : WinWindow
    {
        
        public UITxtApellidoWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtApellido";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinClient UITxtApellidoClient
        {
            get
            {
                if ((this.mUITxtApellidoClient == null))
                {
                    this.mUITxtApellidoClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUITxtApellidoClient.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUITxtApellidoClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUITxtApellidoClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow21 : WinWindow
    {
        
        public UIEntertextWindow21(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "7";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow3 : WinWindow
    {
        
        public UIEntertextWindow3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UITxtCargoWindow : WinWindow
    {
        
        public UITxtCargoWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtCargo";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinClient UITxtCargoClient
        {
            get
            {
                if ((this.mUITxtCargoClient == null))
                {
                    this.mUITxtCargoClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUITxtCargoClient.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUITxtCargoClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUITxtCargoClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow4 : WinWindow
    {
        
        public UIEntertextWindow4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow5 : WinWindow
    {
        
        public UIEntertextWindow5(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "6";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow6 : WinWindow
    {
        
        public UIEntertextWindow6(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "5";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UITxtTelefonoWindow : WinWindow
    {
        
        public UITxtTelefonoWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtTelefono";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinClient UITxtTelefonoClient
        {
            get
            {
                if ((this.mUITxtTelefonoClient == null))
                {
                    this.mUITxtTelefonoClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUITxtTelefonoClient.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUITxtTelefonoClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUITxtTelefonoClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow7 : WinWindow
    {
        
        public UIEntertextWindow7(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "4";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow8 : WinWindow
    {
        
        public UIEntertextWindow8(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "3";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIRegistrarWindow : WinWindow
    {
        
        public UIRegistrarWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "Label";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinText UIRegistrarText
        {
            get
            {
                if ((this.mUIRegistrarText == null))
                {
                    this.mUIRegistrarText = new WinText(this);
                    #region Criterio de búsqueda
                    this.mUIRegistrarText.SearchProperties[WinText.PropertyNames.Name] = "Registrar";
                    this.mUIRegistrarText.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUIRegistrarText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIRegistrarText;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIConfirmacionWindow : WinWindow
    {
        
        public UIConfirmacionWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Confirmacion";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Confirmacion");
            #endregion
        }
        
        #region Properties
        public UIOKWindow1 UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow1(this);
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIOKWindow1 mUIOKWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIOKWindow1 : WinWindow
    {
        
        public UIOKWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "2";
            this.WindowTitles.Add("Confirmacion");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Criterio de búsqueda
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("Confirmacion");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
}
